# Use root/example as user/password credentials
version: '3.1'
services:
  member0:
    container_name: member0
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    networks:
      - mongo-replica-set
    volumes:
      - ./member0:/my-mongo
    depends_on:
      - member1
      - member2
    command: --config /my-mongo/mongod.conf

  member1:
    container_name: member1
    image: mongo:5
    restart: always
    ports:
      - 27018:27017
    networks:
      - mongo-replica-set
    volumes:
      - ./member1:/my-mongo
    command: --config /my-mongo/mongod.conf

  member2:
    container_name: member2
    image: mongo:5
    restart: always
    ports:
      - 27019:27017
    networks:
      - mongo-replica-set
    volumes:
      - ./member2:/my-mongo
    command: --config /my-mongo/mongod.conf

networks:
  mongo-replica-set:
    driver: bridge
